debian/tmp/usr/include/eina-1
debian/tmp/usr/include/eina-cxx-1
debian/tmp/usr/lib/*/libeina.so
debian/tmp/usr/lib/*/pkgconfig/eina*.pc

debian/tmp/usr/include/eo-1
debian/tmp/usr/include/eo-cxx-1
debian/tmp/usr/lib/*/libeo.so
debian/tmp/usr/lib/*/pkgconfig/eo.pc
debian/tmp/usr/lib/*/pkgconfig/eo-cxx.pc
usr/share/eolian/include/eo-1

#libefl
debian/tmp/usr/include/efl-1
debian/tmp/usr/include/efl-cxx-1
usr/lib/*/libefl.so
usr/lib/*/pkgconfig/efl*.pc
usr/share/eolian/include/efl-1
