debian/tmp/usr/include/eina-1
debian/tmp/usr/include/eina-cxx-1
debian/tmp/usr/lib/*/libeina.so
debian/tmp/usr/lib/*/pkgconfig/eina*.pc
usr/lib/*/cmake/Eina/*.cmake
usr/lib/*/cmake/EinaCxx/*.cmake

debian/tmp/usr/include/eo-1
debian/tmp/usr/include/eo-cxx-1
debian/tmp/usr/lib/*/libeo.so
debian/tmp/usr/lib/*/pkgconfig/eo.pc
debian/tmp/usr/lib/*/pkgconfig/eo-cxx.pc
usr/share/eolian/include/eo-1
debian/tmp/usr/share/gdb/auto-load/usr/lib/*/libeo.so.*.py
debian/tmp/usr/share/eo/gdb/eo_gdb.py
usr/lib/*/cmake/Eo/*.cmake
usr/lib/*/cmake/EoCxx/*.cmake

#libefl
debian/tmp/usr/include/efl-1
debian/tmp/usr/include/efl-cxx-1
usr/lib/*/libefl.so
usr/lib/*/libefl.a
usr/lib/*/pkgconfig/efl*.pc
usr/share/eolian/include/efl-1
usr/lib/*/cmake/Efl/*.cmake
