#
# libecore-dev.install
debian/tmp/usr/include/ecore-*
debian/tmp/usr/lib/*/libecore.so
debian/tmp/usr/lib/*/libecore_audio.so
debian/tmp/usr/lib/*/libecore_avahi.so
debian/tmp/usr/lib/*/libecore_con.so
debian/tmp/usr/lib/*/libecore_evas.so
# Conditionally installed from debian/rules (Linux-only):
# debian/tmp/usr/lib/*/libecore_fb.so
debian/tmp/usr/lib/*/libecore_file.so
debian/tmp/usr/lib/*/libecore_imf_evas.so
debian/tmp/usr/lib/*/libecore_imf.so
debian/tmp/usr/lib/*/libecore_input.so
debian/tmp/usr/lib/*/libecore_input_evas.so
debian/tmp/usr/lib/*/libecore_ipc.so
debian/tmp/usr/lib/*/libecore_x.so
debian/tmp/usr/lib/*/libecore_wl2.so
debian/tmp/usr/lib/*/libecore_drm2.so
debian/tmp/usr/lib/*/pkgconfig/ecore*.pc
usr/share/eolian/include/ecore-1
usr/lib/*/cmake/Ecore/*.cmake
usr/lib/*/cmake/EcoreCxx/*.cmake
usr/lib/*/libecore*.a

debian/tmp/usr/include/eldbus-*
debian/tmp/usr/include/eldbus_cxx-*
debian/tmp/usr/lib/*/libeldbus.so
debian/tmp/usr/lib/*/libeldbus.a
debian/tmp/usr/lib/*/pkgconfig/eldbus.pc
usr/lib/*/cmake/Eldbus/*.cmake
usr/share/eolian/include/eldbus-1

#
# libector-dev.install
debian/tmp/usr/lib/*/pkgconfig/ector.pc
debian/tmp/usr/lib/*/libector.so
debian/tmp/usr/lib/*/libector.a
debian/tmp/usr/share/eolian/include/ector-1

#
# libedje-dev.install
debian/tmp/usr/include/edje-1
debian/tmp/usr/include/edje-cxx-1
debian/tmp/usr/lib/*/libedje.so
debian/tmp/usr/lib/*/libedje.a
debian/tmp/usr/lib/*/pkgconfig/edje*.pc
usr/share/eolian/include/edje-1
usr/lib/*/cmake/Edje/*.cmake

#
# libeet-dev.install
debian/tmp/usr/include/eet-1
debian/tmp/usr/include/eet-cxx-1
debian/tmp/usr/lib/*/libeet.so
debian/tmp/usr/lib/*/libeet.a
debian/tmp/usr/lib/*/pkgconfig/eet*.pc
usr/lib/*/cmake/Eet/*.cmake
usr/lib/*/cmake/EetCxx/*.cmake

#
# libeeze-dev.install
debian/tmp/usr/include/eeze-*
debian/tmp/usr/lib/*/libeeze.so
debian/tmp/usr/lib/*/libeeze.a
debian/tmp/usr/lib/*/pkgconfig/eeze.pc
usr/lib/*/cmake/Eeze/*.cmake

#
# libefreet-dev.install
debian/tmp/usr/include/efreet-1/*.h
debian/tmp/usr/lib/*/pkgconfig/efreet.pc
debian/tmp/usr/lib/*/pkgconfig/efreet-mime.pc
debian/tmp/usr/lib/*/pkgconfig/efreet-trash.pc
debian/tmp/usr/lib/*/libefreet.so
debian/tmp/usr/lib/*/libefreet.a
debian/tmp/usr/lib/*/libefreet_mime.so
debian/tmp/usr/lib/*/libefreet_mime.a
debian/tmp/usr/lib/*/libefreet_trash.so
debian/tmp/usr/lib/*/libefreet_trash.a
usr/lib/*/cmake/Efreet/*.cmake

#
# libeina-dev.install
debian/tmp/usr/include/eina-1
debian/tmp/usr/include/eina-cxx-1
debian/tmp/usr/lib/*/libeina.so
debian/tmp/usr/lib/*/libeina.a
debian/tmp/usr/lib/*/pkgconfig/eina*.pc
usr/lib/*/cmake/Eina/*.cmake
usr/lib/*/cmake/EinaCxx/*.cmake

debian/tmp/usr/include/eo-1
debian/tmp/usr/include/eo-cxx-1
debian/tmp/usr/lib/*/libeo.so
debian/tmp/usr/lib/*/libeo.a
debian/tmp/usr/lib/*/pkgconfig/eo.pc
debian/tmp/usr/lib/*/pkgconfig/eo-cxx.pc
usr/share/eolian/include/eo-1
debian/tmp/usr/share/gdb/auto-load/usr/lib/*/libeo.so.*.py
debian/tmp/usr/share/eo/gdb/eo_gdb.py
usr/lib/*/cmake/Eo/*.cmake
usr/lib/*/cmake/EoCxx/*.cmake

#libefl
debian/tmp/usr/include/efl-1
debian/tmp/usr/include/efl-cxx-1
debian/tmp/usr/include/efl-wl-1
usr/lib/*/libefl.so
usr/lib/*/libefl_wl.so
usr/lib/*/libefl.a
usr/lib/*/libefl_wl.a
usr/lib/*/pkgconfig/efl*.pc
usr/share/eolian/include/efl-1
usr/lib/*/cmake/Efl/*.cmake

#
# libeio-dev.install
debian/tmp/usr/include/eio-*/*
debian/tmp/usr/lib/*/libeio.so
debian/tmp/usr/lib/*/libeio.a
debian/tmp/usr/lib/*/pkgconfig/eio*.pc
debian/tmp/usr/share/eolian/include/eio-1
usr/lib/*/cmake/Eio/*.cmake

#
# libelementary-dev.install
debian/tmp/usr/include/elementary-1
debian/tmp/usr/lib/*/libelementary.a
debian/tmp/usr/lib/*/libelementary.so
debian/tmp/usr/lib/*/pkgconfig/elementary.pc
usr/share/eolian/include/elementary-1
usr/lib/*/cmake/Elementary/*.cmake

#
# libelocation-dev.install
debian/tmp/usr/include/elocation-1/*.h
debian/tmp/usr/lib/*/pkgconfig/elocation.pc
debian/tmp/usr/lib/*/libelocation.so
debian/tmp/usr/lib/*/libelocation.a

#
# libelput-dev.install
debian/tmp/usr/include/elput-*
debian/tmp/usr/lib/*/libelput.so
debian/tmp/usr/lib/*/libelput.a
debian/tmp/usr/lib/*/pkgconfig/elput.pc

#
# libelua-dev.install
debian/tmp/usr/include/elua-1
debian/tmp/usr/lib/*/libelua.so
debian/tmp/usr/lib/*/libelua.a
debian/tmp/usr/lib/*/pkgconfig/elua*.pc
debian/tmp/usr/lib/*/cmake/Elua/*.cmake

#
# libembryo-dev.install
debian/tmp/usr/include/embryo-1
debian/tmp/usr/lib/*/libembryo.so
debian/tmp/usr/lib/*/libembryo.a
debian/tmp/usr/lib/*/pkgconfig/embryo.pc

#
# libemile-dev.install
debian/tmp/usr/include/emile-1
debian/tmp/usr/lib/*/libemile.so
debian/tmp/usr/lib/*/libemile.a
debian/tmp/usr/lib/*/pkgconfig/emile*.pc
usr/lib/*/cmake/Emile/*.cmake

#
# libemotion-dev.install
debian/tmp/usr/include/emotion-1
debian/tmp/usr/lib/*/libemotion.so
debian/tmp/usr/lib/*/libemotion.a
debian/tmp/usr/lib/*/pkgconfig/emotion.pc
usr/share/eolian/include/emotion-1
usr/lib/*/cmake/Emotion/*.cmake

#
# libeolian-dev.install
usr/include/eolian*
usr/lib/*/libeolian.so
usr/lib/*/libeolian.a
usr/lib/*/pkgconfig/eolian*.pc
usr/bin/eolian_gen
usr/bin/eolian_cxx
usr/lib/*/cmake/Eolian/*.cmake
usr/lib/*/cmake/EolianCxx/*.cmake

#
# libephysics-dev.install
debian/tmp/usr/include/ephysics-1
debian/tmp/usr/lib/*/libephysics.so
debian/tmp/usr/lib/*/libephysics.a
debian/tmp/usr/lib/*/pkgconfig/ephysics*.pc

#
# libethumb-dev.install
debian/tmp/usr/include/ethumb-1
debian/tmp/usr/include/ethumb-client-1

debian/tmp/usr/lib/*/libethumb.so
debian/tmp/usr/lib/*/libethumb.a
debian/tmp/usr/lib/*/libethumb_client.so
debian/tmp/usr/lib/*/libethumb_client.a

debian/tmp/usr/lib/*/pkgconfig/ethumb.pc
debian/tmp/usr/lib/*/pkgconfig/ethumb_client.pc
usr/lib/*/cmake/Ethumb/*.cmake
usr/lib/*/cmake/EthumbClient/*.cmake

#
# libevas-dev.install
debian/tmp/usr/include/evas-1
debian/tmp/usr/include/evas-cxx-1
debian/tmp/usr/lib/*/libevas.so
debian/tmp/usr/lib/*/libevas.a
debian/tmp/usr/lib/*/pkgconfig/evas*.pc
usr/share/eolian/include/evas-1
usr/lib/*/cmake/Evas/*.cmake
usr/lib/*/cmake/EvasCxx/*.cmake
