debian/tmp/usr/include/ecore-*
debian/tmp/usr/lib/*/libecore.so
debian/tmp/usr/lib/*/libecore_audio.so
debian/tmp/usr/lib/*/libecore_avahi.so
debian/tmp/usr/lib/*/libecore_con.so
debian/tmp/usr/lib/*/libecore_evas.so
# Conditionally installed from debian/rules (Linux-only):
# debian/tmp/usr/lib/*/libecore_fb.so
debian/tmp/usr/lib/*/libecore_file.so
debian/tmp/usr/lib/*/libecore_imf_evas.so
debian/tmp/usr/lib/*/libecore_imf.so
debian/tmp/usr/lib/*/libecore_input.so
debian/tmp/usr/lib/*/libecore_input_evas.so
debian/tmp/usr/lib/*/libecore_ipc.so
debian/tmp/usr/lib/*/libecore_x.so
debian/tmp/usr/lib/*/libecore_wl2.so
debian/tmp/usr/lib/*/libecore_drm2.so
debian/tmp/usr/lib/*/pkgconfig/ecore*.pc
usr/share/eolian/include/ecore-1
usr/lib/*/cmake/Ecore/*.cmake
usr/lib/*/cmake/EcoreCxx/*.cmake
usr/lib/*/libecore*.a

debian/tmp/usr/include/eldbus-*
debian/tmp/usr/include/eldbus_cxx-*
debian/tmp/usr/lib/*/libeldbus.so
debian/tmp/usr/lib/*/libeldbus.a
debian/tmp/usr/lib/*/pkgconfig/eldbus.pc
usr/lib/*/cmake/Eldbus/*.cmake
usr/share/eolian/include/eldbus-1
